[functions]
  external_node_modules = [
    axios,
    cheerio,
    dotenv,
    express,
    mongodb,
    node-cron,
    puppeteer-core
  ]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
